# Generated by Django 3.0.6 on 2020-07-04 04:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('exception', '0014_validate_exception_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validate_exception',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 4, 11, 26, 56, 401207, tzinfo=utc)),
        ),
    ]
